### ISSUE TITLE
PyMISP performance issue

### ISSUE THREAD

**Issue by hel10wor1d** [MISP/PyMISP#207]
**Work environment** 

Questions | Answers
-- | --
Type of issue | Potential Bug?
OS version (server) | Red Hat Enterprise Linux Server release 7.4 
OS version (client) | Windows 10
PHP version | 5.6.25
MISP version / git hash | v2.4.88 / db02fcc4d466590bec47c587102ab66b386d8545
PyMISP version | 2.4.87.1
Browser | N/A

**Concern**

We have been creating a script to make calls to MISP, and noticed that it seems requests via the PyMISP library is can be ~50% slower or more then making pure requests to MISP. Could this be linked to a bug?

For a search that looks for events in the last 5 hours, this the discrepancy that we saw.

_PyMISP time: 0:01:22.506460_
`results_pymisp = PyMISP(misp_url, misp_api_key, False, 'json').search(controller='attributes', type_attribute=types, category=cat, last=time_period, enforceWarninglist=True)`

_Requests time: 0:00:09.762386_
```
url_pull = '{}attributes/restSearch/json'.format(misp_url)
headers_pull = {'Authorization': misp_api_key, 'Content-Type': 'application/json',
                'Accept': 'application/json'}
data_pull = {"request": {"type": types, "category": cat, "last": time_period,
                         "enforceWarnlinglist": "True"}}
requests_response = requests.post(url_pull, headers=headers_pull, json=data_pull, verify=False)
```

I also tired this on a local VM image running on Ubuntu with MISP_v2.4.88, and it seemed a similar issue was occurring.

**Comment by Rafiot** [comment]
This is very weird, @iglocska gave me the same code you gave to him, and the time difference was within .1sec

Can you enable debug in pymisp (`PyMISP(....., debug=True)`) and paste the log? Be careful, it contains the auth key.

**Comment by hel10wor1d** [comment]
This is the output I am getting, when enabling debug. I have removed the large responses due to the size and sanitized the sensitive info. 

I should also mention that one of the bigger feeds we are ingesting is inThreat. Not sure if that makes a difference, but it might help to pull that feed (if not done so already) into your instance for testing to better simulate our environment.

INFO [api.py:81 - __init__() ] To configure logging in your script, leave it to None and use the following: import logging; logging.getLogger('pymisp').setLevel(logging.DEBUG)
DEBUG [api.py:138 - __prepare_request() ] GET - https://[MISP-URL]/servers/getPyMISPVersion.json
DEBUG [api.py:156 - __prepare_request() ] {'User-Agent': 'PyMISP 2.4.87.1 - Python 3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': '[KEY]', 'content-type': 'application/json'}
C:\Users\[user]\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG [api.py:244 - _check_response() ] {
    "version": "2.4.87"
}
DEBUG [api.py:138 - __prepare_request() ] GET - https://[MISP-URL]/attributes/describeTypes.json
DEBUG [api.py:156 - __prepare_request() ] {'User-Agent': 'PyMISP 2.4.87.1 - Python 3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': '[KEY]', 'content-type': 'application/json'}
C:\Users\[]\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG [api.py:244 - _check_response() ] {
.....
......... 
RESPONSE
........
....
DEBUG [api.py:138 - __prepare_request() ] POST - https://[MISP-URL]/attributes/restSearch/download
DEBUG [api.py:140 - __prepare_request() ] {"type": ["ip-dst", "domain"], "category": "Network activity", "last": "5h", "enforceWarninglist": true}
DEBUG [api.py:156 - __prepare_request() ] {'User-Agent': 'PyMISP 2.4.87.1 - Python 3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '104', 'Authorization': '[KEY]', 'content-type': 'application/json'}

**Comment by iglocska** [comment]
Well that is just weird as hell. The request looks to be the same, so what I was worried about isn't the case. Maybe the query is cached? Could you try to do it in the opposite order? :)

**Comment by Rafiot** [comment]
yeah, that's pretty much what I'm doing... Even with a 1y time frame, it is fast.

@iglocska any clue?

**Comment by hel10wor1d** [comment]
Same issue, for running a search in the last 5h :(

Requests time: 0:00:18.022185
PyMISP time: 0:01:23.718224

**Comment by Rafiot** [comment]
How big is the dataset you receive? Could it be enormous and the json loader takes some time? I seriously doubt it, but maybe...

**Comment by adulau** [comment]
@hel10wor1d A small question, what's the memory usage on your server?

**Comment by hel10wor1d** [comment]
@Rafiot A search for the last 5 hours is yielding "47841" attributes with PyMISP. Oddly, there is a discrepancy, as for some reason the same search with just a direct request returns "48123" attributes. I also noticed a slight difference in the entire JSONs output format when I print the response of PyMISP vs. the direct request. Is this to be expected?

PyMISP appears to return the JSON in the following format:
{
	'0': {
		[Attribute's content]
	},
}

The direct request appears to return the results as:
[
	{
		[Attribute's content]
	}
]

@adulau Memory usage on the server, while running the script was about 7GB/15.7GB; the server is actively using about 6-6.5GB. Out of our 16 cores, 3 cores were about at 100% utilization (with all processes running). At some points a spike in all cores were seen while the script was running.

**Comment by Rafiot** [comment]
Can you try with that instead in the direct query:
`data_pull = {"request": {"type": types, "category": cat, "last": time_period, "enforceWarnlinglist": 1}}`
That should fix the difference of attributes returned. 

Is everything up-to-date on your side (PyMISP and MISP)?

**Comment by hel10wor1d** [comment]
I changed the line, and still the same issue. :/

My local PyMISP is running: Version: 2.4.87.1. And I updated our MISP server last Friday, so it should be pretty up to date.

**Comment by Rafiot** [comment]
Do you still have the issue?

**Comment by hel10wor1d** [comment]
I haven't had a chance to re-test, as we still have not upgraded to the latest version. I will let you know though, when I get a chance.

**Comment by hel10wor1d** [comment]
I have since upgraded and tested with the latest version of PyMISP (2.4.92.1) and MISP (2.4.92) instance, and it appears results are fairly comparable to each other now, for results in the last 1 hour. 👍 PyMISP actually won, but my guess its due to caching as when I switch the code around, the direct requests was 2 seconds faster. 

Num of attributes: 41853
Requests time: 0:00:43.103169

Num of attributes: 41853
PyMISP time: 0:00:41.196711

Going to close the issue, as it appears to be resolved. :)
